### ISSUE TITLE
Doesn't work with RabbitMQ.Client 2.8.7

### ISSUE THREAD

**Issue by crmckenzie** [derekgreer/rabbitBus#1]
Your nuspec says you depend on ≥ 2.8.6 && < 3.0,
but when I try to connect via the BusBuilder I get the following error:

System.IO.FileLoadException : Could not load file or assembly 'RabbitMQ.Client, Version=2.8.4.0, Culture=neutral, PublicKeyToken=89e7d7c5feba84ce' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

I'm using RabbitMQ.Cient 2.8.7.

**Comment by derekgreer** [comment]
RabbitBus is compatible with RabbitMQ.Client version 2.8.7, but you have to instruct the fusion loader that version 2.8.7 is what you're choosing to use.  This is an inherent issue with signed assemblies.

To explain, when an assembly A takes a dependency upon a signed assembly B, the assembly loader looks for the exact version of B which was used when A was compiled.

RabbitBus version 1.2.0 was compiled against RabbitMQ.Client version 2.8.4, so that's the version the fusion loader is going to try to load by default.  However, RabbitMQ.Client uses semantic versioning which means that RabbitBus should be compatible with any future releases of RabbitMQ.Client up to the next major version (i.e. 3.0.0).  In order to allow clients of RabbitBus to take advantage of using the latest version of RabbitMQ.Client (e.g. to take advantage of bug fixes or other improvements), the nuspec for RabbitBus specifies a range up to the next major version rather than tying consumers to a specific version of RabbitMQ.Client.  The disadvantage of this is, when you download a particular version of RabbitBus, you're going to get the latest version of RabbitMQ.Client which was released up to version 3.0.  So, when the fusion loader goes to load the RabbitBus assembly, by default it's going to expect to find whatever version it was originally compiled against which may not match the version that NuGet downloaded.

This is where binding redirects come in.  When you have a later version of an assembly than one which one of your dependencies requires, you use binding redirects to instruct the fusion loader to load the newer version instead.  This is a bit of a pain, but fortunately the NuGet Visual Studio add-in automatically adds binding redirects for you when it encounters this issue.  I can only assume that you didn't use NuGet through Visual Studio, or you have a version prior to this feature being added.

Regardless, what you need is a section that looks like this in your config:

``` xml
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="RabbitMQ.Client" publicKeyToken="89e7d7c5feba84ce" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-2.8.7.0" newVersion="2.8.7.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
```

Unfortunately, this is an inherent cost of signed assemblies.
