### ISSUE TITLE
Please include packages.configs in projects so that PackageRestore works from VS build.

### ISSUE THREAD

**Issue by crmckenzie** [derekgreer/rabbitBus#3]

**Comment by derekgreer** [comment]
RabbitBus doesn't use the Visual Studio NuGet plug-in in order to obtain it's dependencies, but rather uses a rake build.  If you would like to build the RabbitBus project from source then you will need to follow the instructions set forth in the [Build_README.txt](https://github.com/derekgreer/rabbitBus/blob/master/BUILD_README.txt) file.
